### ISSUE TITLE
public 里面修改js后刷新变慢

### ISSUE THREAD

**Issue by MRchenfan** [kisnows/Express-Gulp-BrowserSync#1]
文件后服务器自动重启，同时reload会变慢，一直刷新不出来。可能是服务器重启和bs的reload有冲突啊。

**Comment by kisnows** [comment]
嗯，可能是有这个问题，希望我有时间来解决这个问题。
或者你提个 PR 解决这个问题那就更好了。

**Comment by MRchenfan** [comment]
我搭建了另外一个架构，个人觉得前后端分开比较好，即使是搞全栈开发，想想我只是要改改页面，服务器不需要重启啊。而且nodemon不知道能不能设置为只监听routes文件夹，这样后端开发也能自动化而且性能比较合适。

**Comment by kisnows** [comment]
当时搞这套也只是为了解决前端开发问题，用后端渲染纯粹是因为当时前后端不分离，所以要用后端模板，所以前端也就直接用后端模板写了。
