### ISSUE TITLE
代码执行问题

### ISSUE THREAD

**Issue by songxianling** [kisnows/Express-Gulp-BrowserSync#2]
npm run dev是没有问题的；但是终止掉dev后 ；执行npm run api；然后访问地址；无法加载页面
问题解决了；代码没有问题；本地必须同一个端口

**Comment by kisnows** [comment]
run api 是对接后端服务器的，你本地开发的话只需要 dev 就好了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
